-- SHW FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-11
-- Source: SEC + Yahoo
-- currency: USD, units: thousands
--
-- SEC (CIK 89800) and Yahoo Finance agree on all balance sheet fields exactly.
-- Minor SGA discrepancy: SEC=7,695,000 vs Yahoo=7,703,500 (0.11% diff). Using SEC.
-- Minor Operating Profit discrepancy: SEC-derived=3,792,500 vs Yahoo=3,796,700 (0.11% diff). Using SEC-derived.
-- Operating Profit computed: Gross Profit (11,515,500) - SGA (7,695,000) - Other general expense (10,200) - Impairment (17,800) = 3,792,500
-- Liabilities computed: Total Assets (25,901,700) - Total Shareholder Equity (4,598,300) = 21,303,400
-- Balance sheet identity check: 25,901,700 = 21,303,400 + 4,598,300 PASS
--
-- [WARNING] FY2024 DB Operating Profit (3,451,800) matches SEC 2024 Pretax Income exactly,
--   not operating income (~3,734,200 from SEC calculation or 3,761,900 from Yahoo).
--   Consider verifying and correcting FY2024 operating profit in the DB before committing.

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Sherwin-Williams', 2025, '2025-12-31',
  23574300, 12058800, 11515500, 7695000,
  3792500, 2568500, 2318200,
  6007400, 25901700, 6920300,
  21303400, 4598300, 25901700
);
