-- ATZ.TO FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-07
-- Source: Yahoo Finance only (non-American company, no SEC filing)
-- currency: CAD, units: thousands
-- reportDate: 2026-02-28 (fiscal year ending Feb 2026 = DB year 2025)
-- Warnings:
--   [WARNING] No SEC cross-check available — Yahoo Finance only.

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Aritzia', 2025, '2026-02-28',
  3702150, 2040820, 1661330, 1137280,
  524054, 381848, 495197,
  1252450, 3135680, 874919,
  1774650, 1361030, 3135680
);
