-- TJX FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-11
-- Source: SEC + Yahoo Finance
-- currency: USD, units: thousands
-- reportDate: 2026-01-31 (fiscal year ending January 31, 2026 → DB year 2025)
-- SEC and Yahoo values match exactly on all 13 fields — no discrepancies
-- Gross margin: 30.96% (within Off Price benchmark 28–32%)
-- SGA%: 19.07% (in line with 3-year trailing avg 18.87%)
-- Revenue YoY: +7.1% vs FY2024 — normal growth
-- Balance sheet identity: 25,577,000 + 10,190,000 = 35,767,000 ✓

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'TJ Maxx', 2025, '2026-01-31',
  60372000, 41679000, 18693000, 11515000,
  7178000, 5494000, 7297000,
  15202000, 35767000, 13361000,
  25577000, 10190000, 35767000
);
