-- KR FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-11
-- Source: SEC + Yahoo
-- currency: USD, units: thousands
--
-- Fiscal year end: 2026-01-31 (Kroger FY2025)
-- DB year convention: fiscal year ending January → DB year = prior calendar year (2025)
--
-- SGA source: kr_OperatingGeneralAndAdministrativeExpense (OG&A) = $28,308,000K
--   Note: Yahoo SGA ($872,000K) captures only the Rent line — do NOT use Yahoo for KR SGA.
--   Rent ($872,000K) and D&A ($3,332,000K) are excluded from SGA per DB convention.
-- TSE: us-gaap_StockholdersEquity (common shareholders only, $5,927,000K)
--   NCI of $9,000K absorbed into DB Liabilities per KR convention.
-- Inventory: FIFO inventory minus LIFO reserve = $9,445,000K - $2,553,000K = $6,892,000K
--
-- Warnings:
--   [WARNING] Yahoo SGA ($872,000K) vs SEC OG&A ($28,308,000K): Yahoo only captures Rent line. Use SEC.
--   [WARNING] Net Profit dropped sharply from $2,665,000K (FY2024) to $1,016,000K (FY2025),
--             a ~62% decline despite nearly flat revenue. Operating Profit also dropped from
--             $3,849,000K to $1,890,000K (-51%). Investigate underlying cause before applying.
--   [WARNING] FY2024 reportDate in DB is 2025-02-03 but SEC FY2025 comparative shows 2025-02-01.
--             Consider correcting FY2024 reportDate.
--   [WARNING] FY2024 SGA is NULL in DB. SEC FY2025 comparative shows OG&A = $25,431,000K for FY2024.

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Kroger', 2025, '2026-01-31',
  147642000, 113240000, 34402000, 28308000,
  1890000, 1016000, 6892000,
  14505000, 49953000, 18108000,
  44026000, 5927000, 49953000
);
