-- TPR FY2025 (DB year 2024) — new insert
-- Generated by /download-new-year-data on 2026-06-11
-- Source: SEC + Yahoo Finance
-- currency: USD, units: thousands
-- Fiscal year ended: 2025-06-28
-- Notes:
--   Operating Profit includes 854,800K goodwill/intangible impairment (Kate Spade brand
--   revaluation post failed Capri acquisition). One-time charge; values are as-reported.
--   Total Assets dropped from 13,396,300K (DB year 2023) to 6,580,500K due to repayment
--   of ~7B acquisition debt raised for the blocked Tapestry/Capri deal (FTC block Oct 2024).
--   SGA is single combined us-gaap_SellingGeneralAndAdministrativeExpense; no composite needed.
--   All 13 fields confirmed match between SEC 10-K and Yahoo Finance.

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Tapestry', 2024, '2025-06-28',
  7010700, 1721800, 5288900, 4019100,
  415000, 183200, 860700,
  2905600, 6580500, 1556900,
  5722700, 857800, 6580500
);
