-- AMZN FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-07
-- Source: SEC + Yahoo Finance (all values match)
-- currency: USD, units: thousands

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Amazon', 2025, '2025-12-31',
  716924000, 356414000, 360510000, 58301000,
  79975000, 77670000, 38325000,
  229083000, 818042000, 218005000,
  406977000, 411065000, 818042000
);
