-- ETSY FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-11
-- Source: SEC + Yahoo Finance
-- currency: USD, units: thousands
--
-- SGA construction (Rule 4 — no combined SGA tag):
--   us-gaap_SellingAndMarketingExpense:    914,830
--   us-gaap_GeneralAndAdministrativeExpense: 332,766
--   SGA total:                           1,247,596
--   Excluded: us-gaap_ResearchAndDevelopmentExpense (450,192) — product/platform cost, not SGA
--   Excluded: us-gaap_AssetImpairmentCharges (101,703) — one-time impairment charge
--
-- Inventory = NULL: Etsy is a pure marketplace — holds no physical inventory (consistent with all prior DB years)
--
-- [WARNING] Yahoo Operating Income ($367,913K) differs from SEC as-reported ($266,210K).
--           Difference = $101,703K asset impairment charges. SEC as-reported value used.
--
-- Balance sheet identity check:
--   Total Assets:                2,827,254
--   Total Liabilities:           3,925,349
--   Total Shareholder Equity:   -1,098,095
--   Liabilities + TSE:           2,827,254  CHECK: PASS
--
-- Gross Margin: 2,065,701 / 2,883,501 = 71.6% — consistent with prior years (2024: 72.4%, 2023: 69.9%)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Etsy', 2025, '2025-12-31',
  2883501, 817800, 2065701, 1247596,
  266210, 162982, NULL,
  1960983, 2827254, 1363619,
  3925349, -1098095,
  2827254
);
