-- KSS FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-11
-- Source: SEC + Yahoo Finance
-- currency: USD, units: thousands
--
-- Notes:
--   reportDate 2026-01-31 (fiscal year ending late January → DB year = 2025)
--   Net Revenue: us-gaap_RevenueFromContractWithCustomerExcludingAssessedTax = 15,527,000K (SEC)
--   Cost of Goods: us-gaap_CostOfGoodsAndServicesSold = 9,228,000K (SEC, positive)
--   Gross Margin: computed = 15,527,000 - 9,228,000 = 6,299,000K
--   SGA: us-gaap_SellingGeneralAndAdministrativeExpense = 5,089,000K (single combined line; D&A,
--        restructuring/impairment, and legal settlement gain excluded per anomaly rules)
--   Operating Profit: us-gaap_OperatingIncomeLoss = 624,000K (SEC; includes $129M legal
--        settlement gain; Yahoo shows 510,000K excluding gain — SEC is authoritative)
--   Net Profit: us-gaap_NetIncomeLoss = 272,000K (SEC, matches Yahoo)
--   Inventory: us-gaap_InventoryNet = 2,745,000K (SEC, matches Yahoo)
--   Current Assets: us-gaap_AssetsCurrent = 3,691,000K
--   Total Assets: us-gaap_Assets = 13,362,000K
--   Current Liabilities: us-gaap_LiabilitiesCurrent = 2,531,000K
--   TSE: us-gaap_StockholdersEquity = 4,048,000K (no NCI for KSS)
--   Liabilities: computed = 13,362,000 - 4,048,000 = 9,314,000K
--   Total L&SE: us-gaap_LiabilitiesAndStockholdersEquity = 13,362,000K
--   Balance sheet identity: 13,362,000 = 13,362,000 ✓
--
-- [WARNING] Operating Profit: SEC=624,000K, Yahoo=510,000K (>1% discrepancy).
--   Difference = $114M legal settlement gain included in SEC operating income.
--   Using SEC value (624,000K) as authoritative.

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Kohl''s', 2025, '2026-01-31',
  15527000, 9228000, 6299000, 5089000,
  624000, 272000, 2745000,
  3691000, 13362000, 2531000,
  9314000, 4048000, 13362000
);
