-- GAP FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-11
-- Source: SEC + Yahoo Finance
-- currency: USD, units: thousands
--
-- SEC reportDate: 2026-01-31 (fiscal year ending January 31, 2026 → DB year = 2025)
-- SEC and Yahoo Finance values match exactly on all 13 fields.
--
-- SGA: us-gaap_OperatingExpenses = 5,153,000K (sole line between Gross Profit and
--   Operating Income; consistent with prior DB convention for Gap).
-- No composite SGA adjustment needed (no separate marketing or ops-tech lines).
-- No NCI. TSE = us-gaap_StockholdersEquity.
--
-- Balance sheet identity: 12,632,000 = 8,831,000 + 3,801,000 ✓
-- Gross margin: 40.8% (within specialty apparel range 35–55%) ✓
-- Revenue YoY: +1.9% (vs prior year 15,086,000K) ✓
-- GM% vs 3-yr avg (38.1%): +2.7 pp — within 5 pp threshold ✓
-- SGA% vs 3-yr avg (34.6%): -1.1 pp — within 5 pp threshold ✓
--
-- [WARNING] Prior-year reportDate discrepancy: DB year 2024 has reportDate 2025-02-03,
--   but the FY2025 10-K comparative column shows 2025-02-01 as the FY2024 period-end date.
--   The 2-day difference may be a data entry error in the existing DB record for year 2024.
--   Financial data for year 2024 was not changed by this script.

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Gap', 2025, '2026-01-31',
  15366000, 9098000, 6268000, 5153000,
  1115000, 816000, 2207000,
  5777000, 12632000, 3300000,
  8831000, 3801000, 12632000
);
