-- ITX.MC FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-11
-- Source: Yahoo only (non-American company, no SEC filing)
-- currency: EUR, units: thousands
--
-- Anomaly flags:
-- [WARNING] No SEC cross-check available — Yahoo Finance only.
-- [WARNING] SGA not reported by Yahoo Finance for FY2025 (2026-01-31 column shows NaN).
--           SGA estimated from 3-year trailing SGA% average (9.50% of revenue):
--           9.50% × 39,864,200 = ~3,787,099K. This is an estimate — verify against
--           Inditex FY2025 annual report before applying.
--
-- Trend check (3-yr trailing averages):
--   Gross margin%: 3-yr avg 57.52% | FY2025 = 58.25% — OK (within 5pp)
--   SGA%:          3-yr avg  9.50% | FY2025 = ~9.50% (estimated) — OK
--   Revenue YoY:   +3.19% (2024→2025) — OK (within ±50%)
--   Balance sheet: Total Assets 35,638,300 = Liabilities 15,243,100 + TSE 20,395,200 = 35,638,300 — OK
--
-- Notes:
--   Fiscal year ends January 31 each year (Inditex convention). DB year = reportDate year − 1.
--   reportDate 2026-01-31 → DB year = 2025.
--   Gross Margin computed: Net Revenue − Cost of Goods = 39,864,200 − 16,641,700 = 23,222,500.
--   Liabilities computed:  Total Assets − TSE = 35,638,300 − 20,395,200 = 15,243,100.
--   Operating Profit taken from Yahoo "Operating Income" line (8,045,110K).
--   Inditex has no material noncontrolling interest in FY2025; TSE = Stockholders Equity.

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Inditex/Zara', 2025, '2026-01-31',
  39864200, 16641700, 23222500, 3787099,
  8045110, 6220090, 3249160,
  15691200, 35638300, 10171900,
  15243100, 20395200, 35638300
);
