-- CVS FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-11
-- Source: SEC + Yahoo Finance
-- currency: USD, units: thousands
--
-- Notes:
--   Net Revenue: us-gaap_Revenues = $402,067,000K (SEC; matches Yahoo exactly)
--   Cost of Goods: us-gaap_CostOfGoodsAndServicesSold = $221,167,000K (product/service COGS only;
--     consistent with DB convention for all prior years — excludes health care costs /
--     us-gaap_PolicyholderBenefitsAndClaimsIncurredNet = $125,538,000K which is separate)
--   Gross Margin: computed = Net Revenue - Cost of Goods = $180,900,000K
--   SGA: us-gaap_OtherCostAndExpenseOperating (Operating expenses) = $44,977,000K
--     Goodwill impairment (us-gaap_GoodwillImpairmentLoss = $5,725,000K) excluded per anomaly rules
--   Operating Profit: us-gaap_OperatingIncomeLoss = $4,660,000K
--     (lower than FY2024 due to $5,725,000K goodwill impairment on Health Services segment — non-recurring)
--   Net Profit: us-gaap_NetIncomeLoss = $1,768,000K (attributable to CVS Health shareholders)
--   Total Shareholder Equity: us-gaap_StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest
--     = $75,382,000K (total equity including minority interest — consistent with DB convention)
--   Liabilities: computed = Total Assets - TSE = 253,538,000 - 75,382,000 = $178,156,000K
--     (matches us-gaap_Liabilities = $178,156,000K exactly)
--   Balance sheet check: Total Assets 253,538,000 = Liabilities 178,156,000 + TSE 75,382,000 = 253,538,000 ✓
--
-- [WARNING] Yahoo Cost of Revenue ($346,705,000K) includes health care costs. DB uses product-only COGS
--   = $221,167,000K, consistent with all prior years in the database.
-- [WARNING] FY2025 operating profit significantly reduced by $5,725,000K goodwill impairment
--   (Health Services segment). Non-recurring item — lower net profit is expected and valid.

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'CVS', 2025, '2025-12-31',
  402067000, 221167000, 180900000, 44977000,
  4660000, 1768000, 19246000,
  74714000, 253538000, 88692000,
  178156000, 75382000,
  253538000
);
