-- BJ FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-07
-- Source: SEC + Yahoo Finance (all values match within rounding)
-- currency: USD, units: thousands
-- reportDate: 2026-01-31 (fiscal year ending Jan 2026 = DB year 2025)
-- Operating Profit = SEC value (816,604); excludes pre-opening expenses per DB convention.

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'BJ''s', 2025, '2026-01-31',
  21457274, 17457652, 3999622, 3153577,
  816604, 578377, 1555471,
  1990089, 7510475, 2670233,
  5312816, 2197659, 7510475
);
