-- RH FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-11
-- Source: SEC + Yahoo Finance
-- Fiscal year end: 2026-01-31 (January end → DB year = 2025)
-- currency: USD, units: thousands
--
-- SEC cross-check: all fields match Yahoo within rounding (< 0.01% diff)
-- Balance sheet identity: 4,835,710 = 4,775,110 + 60,600 ✓
-- Gross Margin %: 44.1% (within specialty 35–55% range ✓)
-- Revenue YoY: +8.1% (within normal range ✓)
-- SGA %: 32.8% (consistent with 3-year trailing avg of 32.8% ✓)
-- Note: TSE returned to positive (60,600K) from negative (-163,589K in FY2024)
-- SGA: single us-gaap_SellingGeneralAndAdministrativeExpense line; no composite adjustments needed

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'RH', 2025, '2026-01-31',
  3439536, 1923779, 1515757, 1128489,
  387268, 124787, 818550,
  1107662, 4835710, 930606,
  4775110, 60600, 4835710
);
