-- ACI FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-07
-- Source: SEC + Yahoo Finance (all values match; Operating Profit from SEC)
-- currency: USD, units: thousands
-- reportDate: 2026-02-28 (fiscal year ending Feb 2026 = DB year 2025)
-- Warnings:
--   [WARNING] Yahoo Operating Income (715,400) vs SEC (727,600): difference is property
--             gain/loss on dispositions (12,200). SEC is authoritative. Using SEC = 727,600.
--             Consistent with DB convention (2024 DB used SEC operating income, not Yahoo).

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Albertsons', 2025, '2026-02-28',
  83172500, 60565800, 22606700, 21891300,
  727600, 217400, 5173900,
  6715700, 26765900, 7824000,
  24929700, 1836200, 26765900
);
