-- TGT FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-11
-- Source: SEC + Yahoo Finance
-- currency: USD, units: thousands

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Target', 2025, '2026-01-31',
  104780000, 75511000, 29269000, 21535000,
  5117000, 3705000, 12304000,
  20005000, 59490000, 21230000,
  43325000, 16165000, 59490000
);
