-- ADS.DE FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-07
-- Source: Yahoo Finance only (non-American company, no SEC filing)
-- currency: EUR, units: thousands
-- Warnings:
--   [WARNING] No SEC cross-check available — Yahoo Finance only.
-- SGA = Selling & Marketing (8,956,000) + G&A (1,885,000) = 10,841,000
--   Consistent with prior DB convention (Yahoo SGA line used for 2022-2024).

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Adidas', 2025, '2025-12-31',
  24811000, 12006000, 12805000, 10841000,
  2061000, 1340000, 5832000,
  11977000, 20262000, 9094000,
  14486000, 5776000, 20262000
);
