-- DG FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-11
-- Source: SEC + Yahoo Finance
-- currency: USD, units: thousands
-- SEC fiscal year end: 2026-01-30 → DB year = 2025
-- All SEC and Yahoo values match within rounding; SEC used as authoritative source.
-- Balance sheet identity check: 30,963,730 = 22,451,768 + 8,511,962 ✓
-- Gross Margin % = 30.7% (consistent with DG 3-yr trailing avg of 30.4%)
-- SGA % = 25.5% (consistent with DG 3-yr trailing avg of 23.9%, +1.6pp — within threshold)
-- Revenue YoY = +5.2% (from 40,612,308K to 42,724,369K)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Dollar General', 2025, '2026-01-30',
  42724369, 29624680, 13099689, 10896021,
  2203668, 1512311, 6331861,
  7897803, 30963730, 6961135,
  22451768, 8511962, 30963730
);
