-- ASO FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-07
-- Source: SEC + Yahoo Finance (all values match within rounding)
-- currency: USD, units: thousands
-- reportDate: 2026-01-31 (fiscal year ending Jan 2026 = DB year 2025)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Academy Sports', 2025, '2026-01-31',
  6053414, 3947801, 2105613, 1593429,
  512184, 376768, 1503756,
  1954245, 5277036, 1032253,
  3105659, 2171377, 5277036
);
