-- AEO FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-07
-- Source: SEC + Yahoo Finance (all values match within rounding)
-- currency: USD, units: thousands
-- reportDate: 2026-01-31 (fiscal year ending Jan 2026 = DB year 2025)
-- Total SE includes minority interest (per DB convention from prior years).
-- Operating Profit = SEC Operating Income (226,222); includes impairment/restructuring (101,603).

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'American Eagle', 2025, '2026-01-31',
  5547236, 3521915, 2025321, 1485535,
  226222, 191983, 701966,
  1314173, 4009680, 867563,
  2318246, 1691434, 4009680
);
