-- HD FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-11
-- Source: SEC + Yahoo
-- currency: USD, units: thousands
-- reportDate: 2026-02-01 (fiscal year ending February 1, 2026 → DB year = 2025)
-- SEC filing CIK: 354950
-- Cross-check: SEC and Yahoo agree on all 13 fields within rounding tolerance.
-- SGA: Single combined us-gaap_SellingGeneralAndAdministrativeExpense; no composite rule applied.
-- D&A ($3,273,000K) is a separate line item excluded from SGA.
-- Balance sheet identity: Total Assets $105,095,000K = Liabilities $92,282,000K + TSE $12,813,000K ✓
-- Gross margin 33.3% is within Home Improvement expected range (30–35%) ✓
-- No anomalies detected.

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Home Depot', 2025, '2026-02-01',
  164683000, 109818000, 54865000, 30702000,
  20890000, 14156000, 25817000,
  34391000, 105095000, 32424000,
  92282000, 12813000, 105095000
);
