-- ASOMF FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-07
-- Source: Yahoo Finance only (non-American company, no SEC filing)
-- currency: GBP, units: thousands
-- Warnings:
--   [WARNING] No SEC cross-check available — Yahoo Finance only.
--   [WARNING] Gross margin 47.1% is 5.5 pp above 3-year trailing avg of 41.6%.
--             Likely reflects ASOS business restructuring; COGS dropped with revenue.
--   [WARNING] Yahoo SGA (1,199,900) ≈ total operating expense (1,201,700).
--             Confirmed: Marketing (262,300) + G&A (937,600) = 1,199,900 — correct for ASOS cost structure.

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'ASOS', 2025, '2025-08-31',
  2477800, 1311100, 1166700, 1199900,
  -35000, -298400, 402300,
  775300, 1672100, 757400,
  1459700, 212400, 1672100
);
