-- LULU FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-11
-- Source: SEC + Yahoo Finance
-- SEC reportDate: 2026-02-01 (fiscal year ending Feb 1, 2026 → DB year = 2025)
-- currency: USD, units: thousands
-- All values cross-checked: SEC and Yahoo agree within rounding on all 13 fields.
-- No anomalies detected. Balance sheet identity verified.

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Lululemon', 2025, '2026-02-01',
  11102600, 4818468, 6284132, 4066556,
  2210615, 1579183, 1700753,
  4262701, 8456743, 1887548,
  3494903, 4961840, 8456743
);
