-- SIG FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-11
-- Source: SEC + Yahoo Finance
-- currency: USD, units: thousands
-- reportDate: 2026-01-31 (fiscal year ending January 31, 2026 → DB year 2025)
--
-- Notes:
-- [WARNING] Yahoo Operating Income ($515,300K) differs from SEC ($393,100K).
--           Yahoo reports EBIT; SEC us-gaap_OperatingIncomeLoss = $393,100K is authoritative. Using SEC.
-- All other fields match between SEC and Yahoo Finance exactly.
-- SGA: single combined us-gaap_SellingGeneralAndAdministrativeExpense line — no composite rule needed.
-- Gross Margin computed as Net Revenue - Cost of Goods = 6,813,600 - 4,119,000 = 2,694,600.
-- Liabilities computed as Total Assets - Total Shareholder Equity = 5,952,100 - 1,966,200 = 3,985,900.
-- Balance sheet identity check: 5,952,100 = 3,985,900 + 1,966,200 ✓

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Signet Jewelers', 2025, '2026-01-31',
  6813600, 4119000, 2694600, 2173200,
  393100, 294400, 1940100,
  3023500, 5952100, 1888800,
  3985900, 1966200, 5952100
);
