-- BBWI FY2024 and FY2025 — new inserts
-- Generated by /download-new-year-data on 2026-06-07
-- Source: Yahoo Finance only (SEC tool returned errors for both years; CIK 886158 / Jan fiscal year mismatch)
-- currency: USD, units: thousands
-- Warnings:
--   [WARNING] No SEC cross-check available — Yahoo Finance only (both years).
--   [WARNING] Negative Total Shareholder Equity on both years — expected/valid for BBWI.
--   [NOTE] DB rows 2018-2022 are pre-spinoff L Brands data, not comparable to standalone BBWI.

-- FY2024: fiscal year ending 2025-01-31 = DB year 2024
REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Bath & Body Works', 2024, '2025-01-31',
  7307000, 4073000, 3234000, 1968000,
  1266000, 798000, 734000,
  1823000, 4872000, 1231000,
  6257000, -1385000, 4872000
);

-- FY2025: fiscal year ending 2026-01-31 = DB year 2025
REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Bath & Body Works', 2025, '2026-01-31',
  7291000, 4102000, 3189000, 2063000,
  1126000, 649000, 699000,
  2019000, 5069000, 1591000,
  6350000, -1281000, 5069000
);
