-- MC.PA FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-11
-- Source: Yahoo Finance only (non-American company, no SEC filing)
-- currency: EUR, units: thousands

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Louis Vuitton', 2025, '2025-12-31',
  80807000, 27279000, 53528000, 35848000,
  17668000, 10878000, 22659000,
  48179000, 142037000, 30416000,
  74565000, 67472000, 142037000
);
