-- HM-B.ST FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-11
-- Source: Yahoo only (non-American company, no SEC filing)
-- currency: SEK, units: thousands
--
-- Anomaly flags:
-- [WARNING] No SEC cross-check available — Yahoo Finance only.
--
-- Trend check (3-yr trailing averages):
--   Gross margin%: 3-yr avg 51.8% | FY2025 = 53.4% — OK (within 5pp)
--   SGA%:          3-yr avg 40.5% | FY2025 = 37.0% — OK (within 5pp)
--   Revenue YoY:   -2.6% (2024→2025) — OK (within ±50%)
--   Balance sheet: Total Assets 170,273,000 = Liabilities 127,352,000 + TSE 42,921,000 = 170,273,000 — OK
--
-- Note: TSE = Stockholders Equity (common shareholders only, excluding minority interest of 26,000K).
--       Liabilities = Total Assets − TSE (absorbs minority interest).

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'H&M', 2025, '2025-11-30',
  228285000, 106464000, 121821000, 84395000,
  18529000, 12158000, 35427000,
  72495000, 170273000, 61603000,
  127352000, 42921000, 170273000
);
