-- ANF FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-07
-- Source: SEC + Yahoo Finance (all values match within rounding)
-- currency: USD, units: thousands
-- reportDate: 2026-01-31 (fiscal year ending Jan 2026 = DB year 2025)
-- Warnings:
--   [WARNING] SGA% 3-year trailing avg skewed by 2022 using older (narrower) SGA reporting basis.
--             On 2023-2024 basis, 2025 SGA% 48.1% is within range (avg 50.5%). Not a data concern.

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Abercrombie & Fitch', 2025, '2026-01-31',
  5266292, 2028884, 3237408, 2535104,
  699143, 506921, 601218,
  1650464, 3541874, 1106000,
  2137979, 1403895, 3541874
);
