-- AD.AS FY2025 — new insert
-- Generated by /download-new-year-data on 2026-06-07
-- Source: Yahoo Finance only (non-American company, no SEC filing)
-- currency: EUR, units: thousands
-- Warnings:
--   [WARNING] No SEC cross-check available — Yahoo Finance only.
-- SGA = Selling & Marketing (17,722,000) + G&A (3,710,000) = 21,432,000
--   Consistent with prior DB convention (Yahoo SGA line used for all prior years).
--   Ahold Delhaize reports no separate other-operating line; SGA = total operating expense by design.

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Ahold Delhaize', 2025, '2025-12-31',
  92352000, 67838000, 24514000, 21432000,
  3082000, 2264000, 4795000,
  11923000, 49089000, 16794000,
  34894000, 14195000, 49089000
);
