-- ============================================================
-- WOOF — New company setup
-- Generated by /create-new-company-sql on 2026-06-01
-- ============================================================

-- ============================================================
-- Section A — Company Info
-- ============================================================

INSERT INTO company_info (
  company, CIK, display_name, ticker_symbol,
  segment, subsegment, currency, units
) VALUES (
  'Petco', 1826470, 'Petco Health & Wellness Company', 'WOOF',
  'Health & Pharmacy', NULL, 'USD', 'thousands'
);

-- ============================================================
-- Section B — Financials: Petco (WOOF) — FY2021 to FY2025
-- ============================================================

-- Petco FY2021 — New insert
REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Petco', 2021, '2022-01-29',
  5807149, 3380539, 2426610, 2160539,
  266071, 164417, 675111,
  1070777, 6497941, 1053139,
  4242122, 2255819, 6497941
);

-- Petco FY2022 — New insert
REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Petco', 2022, '2023-01-28',
  6035967, 3608860, 2427107, 2201548,
  225559, 90801, 652430,
  1015994, 6612829, 1021258,
  4231352, 2381477, 6612829
);

-- Petco FY2023 — New insert
REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Petco', 2023, '2024-02-03',
  6255284, 3901449, 2353835, 2311625,
  -1180314, -1280210, 684502,
  951744, 5363152, 1113143,
  4178723, 1184429, 5363152
);

-- Petco FY2024 — New insert
REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Petco', 2024, '2025-02-01',
  6116462, 3792060, 2324402, 2317351,
  7051, -101816, 653329,
  973619, 5194430, 1139163,
  4080800, 1113630, 5194430
);

-- Petco FY2025 — New insert
REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Petco', 2025, '2026-01-31',
  5961467, 3656395, 2305072, 2184639,
  120433, 9066, 590210,
  1019786, 5173425, 1134141,
  4009171, 1164254, 5173425
);
