-- ACI FY2025 — new insert
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (2026-02-28); Total Revenue used for Net Revenue per DB convention
-- Operating Profit uses Total Operating Income As Reported per Albertsons DB pattern

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Albertsons', 2025, '2026-02-28',
  83172500, 60565800, 22606700, 21891300,
  727600, 217400, 5173900,
  6715700, 26765900, 7824000,
  24929700, 1836200, 26765900
);
