-- ACI FY2018 — Correction: SGA (16,107,300→16,272,300)
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC FY2020 10-K comparative (2019-02-23); actual SGA line = 16,272,300K
-- Prior value 16,107,300K incorrectly netted $165M property disposition gain against SGA
-- (Gain is already reflected in Operating Profit; SGA should be the standalone expense line)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Albertsons', 2018, '2019-02-23',
  60534500, 43639900, 16894600, 16272300,
  787300, 131100, 4332800,
  6250000, 20776600, 5152700,
  19325900, 1450700, 20776600
);

-- ACI FY2024 — Correction: reportDate (2025-02-24→2025-02-22)
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC 10-K header = 2025-02-22; all financial values unchanged

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Albertsons', 2024, '2025-02-22',
  80390900, 58135300, 22255600, 20613700,
  1546100, 958600, 4989000,
  6559000, 26755700, 7251000,
  23369800, 3385900, 26755700
);

-- ACI FY2025 — New insert
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (2026-02-28); Total Revenue used for Net Revenue per DB convention

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Albertsons', 2025, '2026-02-28',
  83172500, 60565800, 22606700, 21891300,
  727600, 217400, 5173900,
  6715700, 26765900, 7824000,
  24929700, 1836200, 26765900
);
