-- Fix CIK in company_info (was NULL, correct CIK = 869425)
-- Royal Ahold Delhaize N.V. files 20-F as foreign private issuer; CIK confirmed via SEC EDGAR
UPDATE company_info SET CIK = 869425 WHERE ticker_symbol = 'AD.AS';

-- AD.AS FY2025 — new insert
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (2025-12-31); values in thousands of euros (EUR)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Ahold Delhaize', 2025, '2025-12-31',
  92352000, 67838000, 24514000, 21432000,
  3082000, 2264000, 4795000,
  11923000, 49089000, 16794000,
  34894000, 14195000, 49089000
);
