-- Fix CIK in company_info (was NULL, correct CIK = 1011311)
-- Adidas AG files 20-F as foreign private issuer; CIK confirmed via SEC EDGAR
UPDATE company_info SET CIK = 1011311 WHERE ticker_symbol = 'ADS.DE';

-- ADS.DE FY2025 — new insert
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (2025-12-31); values in thousands of euros (EUR)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Adidas', 2025, '2025-12-31',
  24811000, 12006000, 12805000, 10841000,
  2061000, 1340000, 5832000,
  11977000, 20262000, 9094000,
  14486000, 5776000, 20262000
);
