-- AEO FY2024 — Correction: reportDate (2025-02-03→2025-02-01)
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC 10-K period header = 2025-02-01; all financial values unchanged

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'American Eagle', 2024, '2025-02-01',
  5328650, 3239720, 2088930, 1431810,
  427303, 329380, 636655,
  1354231, 3830775, 882656,
  2063915, 1766860, 3830775
);

-- AEO FY2025 — New insert
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (2026-01-31); Operating Profit = Total Operating Income As Reported

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'American Eagle', 2025, '2026-01-31',
  5547240, 3521920, 2025320, 1485540,
  226222, 191983, 701966,
  1314170, 4009680, 867563,
  2318250, 1691430, 4009680
);
