-- AEO FY 2025 — new insert
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (column 2026-01-31); Operating Profit = Total Operating Income As Reported (AEO convention)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'American Eagle', 2025, '2026-01-31',
  5547240, 3521920, 2025320, 1485540,
  226222, 191983, 701966,
  1314170, 4009680, 867563,
  2318250, 1691430, 4009680
);
