-- AMZN FY2020 — correction: Liabilities (101,408,000→227,791,000)
-- Generated by /insert-financials on 2026-05-29
-- Source: Derived from existing Dolt values (Total Assets - TSE = 321,195,000 - 93,404,000)
-- Original value captured only non-current liabilities; corrected to total liabilities

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Amazon', 2020, '2020-12-31',
  386064000, 233307000, 152757000, 28676000,
  22899000, 21331000, 23795000,
  132733000, 321195000, 126385000,
  227791000, 93404000, 321195000
);

-- AMZN FY2025 — new insert
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (2025-12-31); SGA excludes Technology & Content per company-notes

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Amazon', 2025, '2025-12-31',
  716924000, 356414000, 360510000, 58301000,
  79975000, 77670000, 38325000,
  229083000, 818042000, 218005000,
  406977000, 411065000, 818042000
);
