-- ============================================================
-- AMZN (Amazon) — Multi-year financial insert
-- Generated by /insert-financials on 2026-06-03
-- Source: /verify-dolt-db-financials skill
-- FY2019: SGA correction (24,290,000→24,081,000 — removes ~209K; correct = Marketing+G&A only)
-- FY2020: Liabilities correction (101,408,000→227,791,000 — was below Current Liabilities, impossible)
-- FY2021: SGA correction (41,436,000→41,374,000 — removes 62K "Other op expense" per anomaly rules)
-- FY2022: SGA correction (55,392,000→54,129,000 — removes 1,263K restructuring per anomaly rules)
-- FY2025: New insert
-- FY2018: Confirmed ✓ (verified vs SEC FY2018 10-K — all fields match)
-- NOTE: Amazon SGA = Marketing + G&A only. Technology & Content and Other op expense excluded.
-- ============================================================

-- AMZN FY2019 — Correction: SGA (24,290,000→24,081,000)
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC FY2019 10-K (2019-12-31); Marketing (18,878,000) + G&A (5,203,000) = 24,081,000
-- Prior value 24,290,000 incorrectly included ~209K additional; all other fields confirmed ✓

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Amazon', 2019, '2019-12-31',
  280522000, 165536000, 114986000, 24081000,
  14541000, 11588000, 20497000,
  96334000, 225248000, 87812000,
  163188000, 62060000, 225248000
);

-- AMZN FY2020 — Correction: Liabilities (101,408,000→227,791,000)
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC FY2022 10-K comparative (2020-12-31); Liabilities = Total Assets − TSE

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Amazon', 2020, '2020-12-31',
  386064000, 233307000, 152757000, 28676000,
  22899000, 21331000, 23795000,
  132733000, 321195000, 126385000,
  227791000, 93404000, 321195000
);

-- AMZN FY2021 — Correction: SGA (41,436,000→41,374,000)
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC FY2022 10-K comparative (2021-12-31); removed 62K "Other operating expense" (restructuring)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Amazon', 2021, '2021-12-31',
  469822000, 272344000, 197478000, 41374000,
  24879000, 33364000, 32640000,
  161580000, 420549000, 142266000,
  282304000, 138245000, 420549000
);

-- AMZN FY2022 — Correction: SGA (55,392,000→54,129,000)
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC FY2022 10-K + Yahoo Finance; removed 1,263K "Other operating expense" (layoff restructuring)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Amazon', 2022, '2022-12-31',
  513983000, 288831000, 225152000, 54129000,
  12248000, -2722000, 34405000,
  146791000, 462675000, 155393000,
  316632000, 146043000, 462675000
);

-- AMZN FY2025 — New insert
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC FY2025 10-K (2025-12-31) + Yahoo Finance (all fields confirmed)
-- SGA = Marketing (47,129,000) + G&A (11,172,000) = 58,301,000K; Other op expense (4,639,000K) excluded

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Amazon', 2025, '2025-12-31',
  716924000, 356414000, 360510000, 58301000,
  79975000, 77670000, 38325000,
  229083000, 818042000, 218005000,
  406977000, 411065000, 818042000
);
