-- ============================================================
-- ANF (Abercrombie & Fitch) — Multi-year financial insert
-- Generated by /insert-financials on 2026-06-03
-- Source: /verify-dolt-db-financials skill
-- FY2018–2022: SGA corrected (was MG&A only; now StoresAndDist + MG&A combined)
--              Net Profit corrected (was ProfitLoss incl. NCI; now NetIncomeLoss A&F only)
--              FY2020 also had wrong sign (was +108,954, corrected to -103,887)
-- FY2024: reportDate correction only (2025-02-03 → 2025-02-01)
-- FY2025: New insert
-- ============================================================

-- ANF FY2018 — Correction: SGA (484,863→2,021,079), Net Profit (78,808→74,541)
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC FY2019 10-K comparative (2019-02-02); balance sheet unchanged (pre-ASC 842)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Abercrombie & Fitch', 2018, '2019-02-02',
  3590109, 1430193, 2159916, 2021079,
  127366, 74541, 437879,
  1335950, 2385593, 558917,
  1176693, 1208900, 2385593
);

-- ANF FY2019 — Correction: SGA (464,615→2,015,858), Net Profit (44,960→39,358)
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC FY2019 10-K (2020-02-01); all balance sheet fields confirmed

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Abercrombie & Fitch', 2019, '2020-02-01',
  3623073, 1472155, 2150918, 2015858,
  70068, 39358, 434326,
  1264749, 3549665, 815354,
  2478487, 1071178, 3549665
);

-- ANF FY2020 — Correction: SGA (463,843→1,843,791), Net Profit sign+value (108,954→-103,887)
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC FY2022 10-K comparative (2021-01-30); balance sheet unverified (identity ✓)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Abercrombie & Fitch', 2020, '2021-01-30',
  3125384, 1234179, 1891205, 1843791,
  -20469, -103887, 404053,
  1661629, 3314902, 959399,
  2365590, 949312, 3314902
);

-- ANF FY2021 — Correction: SGA (536,815→1,965,138), Net Profit (270,066→263,010)
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC FY2022 10-K comparative (2022-01-29); balance sheet unverified (identity ✓)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Abercrombie & Fitch', 2021, '2022-01-29',
  3712768, 1400773, 2311995, 1965138,
  343084, 263010, 525864,
  1507759, 2939491, 1015240,
  2102167, 837324, 2939491
);

-- ANF FY2022 — Correction: SGA (517,602→2,014,560), Net Profit (10,385→2,816)
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC FY2022 10-K + FY2023 restated comparative; Yahoo confirms; balance sheet confirmed

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Abercrombie & Fitch', 2022, '2023-01-28',
  3697751, 1593213, 2104538, 2014560,
  92648, 2816, 505621,
  1228018, 2713100, 902200,
  2006531, 706569, 2713100
);

-- ANF FY2024 — Correction: reportDate only (2025-02-03→2025-02-01)
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC FY2024 10-K (2025-02-01); all financial values confirmed, no change

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Abercrombie & Fitch', 2024, '2025-02-01',
  4948587, 1773926, 3174661, 2440473,
  740820, 566223, 575005,
  1673431, 3299887, 1126944,
  1948564, 1351323, 3299887
);

-- ANF FY2025 — New insert
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC FY2025 10-K (2026-01-31) + Yahoo Finance (all fields confirmed)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Abercrombie & Fitch', 2025, '2026-01-31',
  5266292, 2028884, 3237408, 2535104,
  699143, 506921, 601218,
  1650464, 3541874, 1106000,
  2121463, 1420411, 3541874
);
