-- ANF FY2022 — correction: SGA (517,602→2,014,560), Net Profit (10,385→2,816)
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (2023-01-31); SGA corrected to full Selling General And Administration;
--         Net Profit corrected to Net Income Common Stockholders (consistent with FY2023/FY2024)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Abercrombie & Fitch', 2022, '2023-01-28',
  3697751, 1593213, 2104538, 2014560,
  92648, 2816, 505621,
  1228018, 2713100, 902200,
  2006531, 706569, 2713100
);

-- ANF FY2025 — new insert
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (2026-01-31)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Abercrombie & Fitch', 2025, '2026-01-31',
  5266290, 2028880, 3237410, 2535100,
  699143, 506921, 601218,
  1650460, 3541870, 1106000,
  2121460, 1420410, 3541870
);
