-- ASO FY2024 — Correction: reportDate (2025-02-03→2025-02-01)
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC 10-K period header = 2025-02-01; all financial values unchanged

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Academy Sports', 2024, '2025-02-01',
  5933450, 3921990, 2011460, 1472821,
  538639, 418447, 1308840,
  1710149, 4900963, 960881,
  2896928, 2004035, 4900963
);

-- ASO FY2025 — New insert
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (2026-01-31); Net Revenue uses Total Revenue per DB convention

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Academy Sports', 2025, '2026-01-31',
  6053410, 3947800, 2105610, 1593430,
  512184, 376768, 1503760,
  1954240, 5277040, 1032250,
  3105660, 2171380, 5277040
);
