-- ASO FY2025 — new insert
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (2026-01-31); Net Revenue uses Total Revenue per DB convention

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Academy Sports', 2025, '2026-01-31',
  6053410, 3947800, 2105610, 1593430,
  512184, 376768, 1503760,
  1954240, 5277040, 1032250,
  3105660, 2171380, 5277040
);
