-- ASOMF FY2024 — correction: SGA (1,496,400→1,340,800), Operating Profit (-331,900→-187,000)
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (2024-08-31); restructuring charges and D&A removed from SGA per anomaly rules

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'ASOS', 2024, '2024-08-31',
  2905800, 1743300, 1162500, 1340800,
  -187000, -338700, 520300,
  1146400, 2271200, 714000,
  1749900, 521300, 2271200
);

-- ASOMF FY2025 — new insert
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (2025-08-31); Operating Profit uses clean Yahoo "Operating Income" (pre-exceptional)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'ASOS', 2025, '2025-08-31',
  2477800, 1311100, 1166700, 1199900,
  -35000, -298400, 402300,
  775300, 1672100, 757400,
  1459700, 212400, 1672100
);
