-- ASOMF FY2022 — Correction: Operating Profit (33,400→-9,800)
-- Generated by /insert-financials on 2026-06-03
-- Source: Yahoo Finance "Total Operating Income As Reported" (-9,800K = GAAP reported);
--         prior value 33,400K was Yahoo's adjusted/underlying figure excluding special charges

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'ASOS', 2022, '2022-08-31',
  3936500, 2219000, 1717500, 1694000,
  -9800, -30800, 1078400,
  1554000, 2996900, 1040000,
  1982000, 1014900, 2996900
);

-- ASOMF FY2024 — Correction: SGA (1,496,400→1,340,800), Operating Profit (-331,900→-187,000)
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (2024-08-31); restructuring charges and D&A removed from SGA per anomaly rules

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'ASOS', 2024, '2024-08-31',
  2905800, 1743300, 1162500, 1340800,
  -187000, -338700, 520300,
  1146400, 2271200, 714000,
  1749900, 521300, 2271200
);

-- ASOMF FY2025 — New insert
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (2025-08-31)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'ASOS', 2025, '2025-08-31',
  2477800, 1311100, 1166700, 1199900,
  -35000, -298400, 402300,
  775300, 1672100, 757400,
  1459700, 212400, 1672100
);
