-- ATZ.TO FY 2025 — new insert
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (column 2026-02-28); non-US company (Canadian), no SEC filing; values in CAD thousands

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Aritzia', 2025, '2026-02-28',
  3702150, 2040820, 1661330, 1137280,
  524054, 381848, 495197,
  1252450, 3135680, 874919,
  1774650, 1361030, 3135680
);
