-- ============================================================
-- BABA (Alibaba) — Multi-year financial insert
-- Generated by /insert-financials on 2026-06-03
-- Source: /verify-dolt-db-financials skill
-- FY2018–2024: TSE correction only (was Common Stock Equity, must be Total Equity incl. NCI)
--              All other fields unchanged from Dolt.
-- FY2025: New insert (Yahoo Finance, RMB converted at ~7.26 USD/RMB)
-- NOTE: Alibaba files 20-F (not 10-K); SEC MCP cannot verify. Yahoo-only.
-- NOTE: FY2025 operating profit 6,908K is down 64% YoY — verify against 20-F.
-- ============================================================

-- BABA FY2018 — Correction: TSE (73,348,000 → 91,697,000)
-- Generated by /insert-financials on 2026-06-03
-- Source: Dolt (all fields except TSE); TSE = Total Assets − Liabilities per anomaly rules

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Alibaba', 2018, '2019-03-31',
  56152000, 30833000, 25319000, 9636000,
  8506000, 13095000, NULL,
  40272000, 143801000, 30944000,
  52104000, 91697000, 143801000
);

-- BABA FY2019 — Correction: TSE (106,683,000 → 124,231,000)
-- Generated by /insert-financials on 2026-06-03
-- Source: Dolt (all fields except TSE); TSE = Total Assets − Liabilities per anomaly rules

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Alibaba', 2019, '2020-03-31',
  71985000, 39878000, 32107000, 11138000,
  12912000, 21104000, NULL,
  65377000, 185429000, 34159000,
  61198000, 124231000, 185429000
);

-- BABA FY2020 — Correction: TSE (143,086,000 → 165,395,000)
-- Generated by /insert-financials on 2026-06-03
-- Source: Dolt (all fields except TSE); TSE = Total Assets − Liabilities per anomaly rules

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Alibaba', 2020, '2021-03-31',
  109480000, 64289000, 45191000, 20871000,
  13688000, 22983000, NULL,
  98196000, 257978000, 57596000,
  92583000, 165395000, 257978000
);

-- BABA FY2021 — Correction: TSE (149,619,000 → 170,712,000)
-- Generated by /insert-financials on 2026-06-03
-- Source: Dolt (all fields except TSE); TSE = Total Assets − Liabilities per anomaly rules

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Alibaba', 2021, '2022-03-31',
  134567000, 85096000, 49471000, 23934000,
  10985000, 9820000, NULL,
  100726000, 267467000, 60540000,
  96755000, 170712000, 267467000
);

-- BABA FY2022 — Correction: TSE (144,105,000 → 163,510,000)
-- Generated by /insert-financials on 2026-06-03
-- Source: Dolt (all fields except TSE); TSE = Total Assets − Liabilities per anomaly rules

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Alibaba', 2022, '2023-03-31',
  126491000, 80042000, 46449000, 21212000,
  14612000, 10598000, NULL,
  101632000, 255263000, 56111000,
  91753000, 163510000, 255263000
);

-- BABA FY2023 — Correction: TSE (136,635,000 → 154,093,000)
-- Generated by /insert-financials on 2026-06-03
-- Source: Dolt (all fields except TSE); TSE = Total Assets − Liabilities per anomaly rules

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Alibaba', 2023, '2024-03-31',
  130350000, 81205000, 49145000, 21762000,
  15699000, 11081000, NULL,
  104270000, 244426000, 58378000,
  90333000, 154093000, 244426000
);

-- BABA FY2024 — Correction: TSE (139,162,000 → 150,220,000)
-- Generated by /insert-financials on 2026-06-03
-- Source: Dolt (all fields except TSE); TSE = Total Assets − Liabilities per anomaly rules

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Alibaba', 2024, '2025-03-31',
  137300000, 82446000, 54854000, 25943000,
  19417000, 17929000, NULL,
  92886000, 248629000, 59992000,
  98409000, 150220000, 248629000
);

-- BABA FY2025 — New insert
-- Generated by /insert-financials on 2026-06-03
-- Source: Yahoo Finance (column 2026-03-31); RMB converted at ~7.26 USD/RMB
-- IMPORTANT: Verify FX rate and FY2025 operating profit decline against 20-F when available

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Alibaba', 2025, '2026-03-31',
  141001000, 84866000, 56135000, 38306000,
  6908000, 14269000, NULL,
  84128000, 263028000, 65621000,
  107890000, 155138000, 263028000
);
