-- BABA FY2025 — new insert
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (2026-03-31); values in thousands USD
-- IMPORTANT: RMB converted at estimated rate ~7.27 RMB/USD (March 31, 2026)
-- VERIFY actual exchange rate before applying. Also verify SGA spike (+47.7% YoY) is correct.

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Alibaba', 2025, '2026-03-31',
  140807000, 84750000, 56057000, 38254000,
  6899000, 14248000, NULL,
  84013000, 262664000, 65530000,
  107745000, 145924000, 262664000
);
