-- BBW FY 2018 — Correction: Operating Profit changed from −18,507 (Pre-tax Income) to −18,422 (Gross − SGA)
-- Generated by /insert-financials on 2026-06-06
-- Source: SEC

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Build-A-Bear', 2018, '2019-02-02',
  336585, 197831, 138754, 157176,
  -18422, -17933, 58356,
  99798, 172046, 56177,
  77732, 94314, 172046
);

-- BBW FY 2019 — Correction: Operating Profit changed from 1,561 (Pre-tax Income) to 1,576 (Gross − SGA)
-- Generated by /insert-financials on 2026-06-06
-- Source: SEC

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Build-A-Bear', 2019, '2020-02-01',
  338543, 184920, 153623, 152047,
  1576, 261, 53381,
  98750, 297262, 85964,
  208631, 88631, 297262
);

-- BBW FY 2020 — Correction: Operating Profit changed from −20,186 (Pre-tax Income) to −20,176 (Gross − SGA, excl. impairment)
-- Generated by /insert-financials on 2026-06-06
-- Source: SEC

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Build-A-Bear', 2020, '2021-01-30',
  255310, 157901, 97409, 117585,
  -20176, -22983, 46947,
  100193, 261372, 89328,
  194064, 67308, 261372
);

-- BBW FY 2025 — New insert — Yahoo Finance data available; SEC 10-K not yet filed
-- Generated by /insert-financials on 2026-06-06
-- Source: Yahoo
-- NOTE: reportDate 2026-01-31 is a placeholder from Yahoo; confirm from SEC 10-K when filed (expected March–April 2026)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Build-A-Bear', 2025, '2026-01-31',
  529832, 234203, 295629, 229203,
  66426, 52203, 82203,
  140020, 345453, 90626,
  190425, 155028, 345453
);
