-- BBWI FY 2022 — correction (all fields)
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (column 2023-01-31); prior Dolt data was incorrect (wrong source/period)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Bath & Body Works', 2022, '2023-01-31',
  7560000, 4305000, 3255000, 1879000,
  1376000, 800000, 709000,
  2266000, 5494000, 1379000,
  7700000, -2206000, 5494000
);

-- BBWI FY 2024 — new insert
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (column 2025-01-31)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Bath & Body Works', 2024, '2025-01-31',
  7307000, 4073000, 3234000, 1968000,
  1266000, 798000, 734000,
  1823000, 4872000, 1231000,
  6257000, -1385000, 4872000
);

-- BBWI FY 2025 — new insert
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (column 2026-01-31)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Bath & Body Works', 2025, '2026-01-31',
  7291000, 4102000, 3189000, 2063000,
  1126000, 649000, 699000,
  2019000, 5069000, 1591000,
  6350000, -1281000, 5069000
);
