-- ============================================================
-- BBWI (Bath & Body Works) — Multi-year financial insert
-- Generated by /insert-financials on 2026-06-03
-- Source: /verify-dolt-db-financials skill
-- CIK correction: 886158 (BBBY — WRONG) → 701985 (L Brands/BBWI)
-- Years covered: 2018–2025
--   2018–2020: L Brands combined (B&BW + Victoria's Secret pre-spinoff)
--   2021–2022: BBWI standalone (was BBBY data)
--   2023: reportDate correction only
--   2024–2025: New inserts
-- ============================================================

-- PREREQUISITE: Fix wrong CIK in company_info
-- CIK 886158 belongs to Bed Bath & Beyond (BBBY), not BBWI
UPDATE company_info SET CIK = 701985 WHERE ticker_symbol = 'BBWI';

-- ============================================================

-- BBWI FY2018 — Correction: ALL fields (was BBBY data)
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC 10-K CIK 701985 (L Brands combined — includes B&BW + Victoria's Secret segments)
-- NOTE: Revenue $13.2B includes VS; not comparable to BBWI standalone FY2021+ ($7.9B)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Bath & Body Works', 2018, '2019-02-02',
  13237000, 8338000, 4899000, 3563000,
  1237000, 644000, 1248000,
  3260000, 8090000, 1986000,
  8959000, -869000, 8090000
);

-- BBWI FY2019 — Correction: ALL fields (was BBBY data)
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC 10-K CIK 701985 (L Brands combined — includes B&BW + Victoria's Secret segments)
-- NOTE: Op Profit 258,000K includes $720M VS goodwill impairment; Net Profit is a loss (-366,000K)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Bath & Body Works', 2019, '2020-02-01',
  12914000, 8464000, 4450000, 3472000,
  258000, -366000, 1287000,
  3245000, 10125000, 2372000,
  11624000, -1499000, 10125000
);

-- BBWI FY2020 — Correction: ALL fields (was BBBY data)
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC 10-K CIK 701985 (L Brands combined — final pre-spinoff year; VS spun off Aug 2021)
-- NOTE: High Current Assets ($5.6B) due to $3.9B cash buildup during COVID

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Bath & Body Works', 2020, '2021-01-30',
  11847000, 7180000, 4667000, 3087000,
  1580000, 844000, 1273000,
  5579000, 11571000, 2826000,
  12233000, -662000, 11571000
);

-- BBWI FY2021 — Correction: ALL fields (was BBBY data)
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC 10-K CIK 701985 (first BBWI standalone year; VS spinoff gain $258M in Net Profit)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Bath & Body Works', 2021, '2022-01-29',
  7882000, 4027000, 3855000, 1846000,
  2009000, 1333000, 709000,
  3009000, 6026000, 1290000,
  7544000, -1518000, 6026000
);

-- BBWI FY2022 — Correction: ALL fields (was BBBY data) + reportDate fix
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC 10-K CIK 701985 + Yahoo Finance (all fields confirmed)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Bath & Body Works', 2022, '2023-01-28',
  7560000, 4305000, 3255000, 1879000,
  1376000, 800000, 709000,
  2266000, 5494000, 1379000,
  7700000, -2206000, 5494000
);

-- BBWI FY2023 — Correction: reportDate only (2024-01-31 → 2024-02-03)
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC 10-K CIK 701985 + Yahoo + Dolt (financials confirmed; only reportDate changed)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Bath & Body Works', 2023, '2024-02-03',
  7429000, 4193000, 3236000, 1951000,
  1285000, 878000, 710000,
  2115000, 5463000, 1289000,
  7090000, -1627000, 5463000
);

-- BBWI FY2024 — New insert
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC 10-K CIK 701985 (period ending 2025-02-01) + Yahoo Finance (all fields confirmed)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Bath & Body Works', 2024, '2025-02-01',
  7307000, 4073000, 3234000, 1968000,
  1266000, 798000, 734000,
  1823000, 4872000, 1231000,
  6257000, -1385000, 4872000
);

-- BBWI FY2025 — New insert
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC 10-K CIK 701985 (period ending 2026-01-31) + Yahoo Finance (all fields confirmed)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Bath & Body Works', 2025, '2026-01-31',
  7291000, 4102000, 3189000, 2063000,
  1126000, 649000, 699000,
  2019000, 5069000, 1591000,
  6350000, -1281000, 5069000
);
