-- BBY FY 2024 — Correction: reportDate (2025-02-03 → 2025-02-01)
-- Generated by /insert-financials on 2026-06-06
-- Source: SEC 10-K (CIK 764478)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Best Buy', 2024, '2025-02-01',
  41528000, 32143000, 9385000, 7651000,
  1262000, 927000, 5085000,
  8224000, 14782000, 8016000,
  11974000, 2808000, 14782000
);

-- BBY FY 2025 — New insert
-- Generated by /insert-financials on 2026-06-06
-- Source: SEC 10-K (CIK 764478, FY2025 ending 2026-01-31)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Best Buy', 2025, '2026-01-31',
  41691000, 32318000, 9373000, 7623000,
  1389000, 1069000, 5230000,
  8504000, 14670000, 7679000,
  11706000, 2964000, 14670000
);
