-- BJ FY2020 — Correction: Operating Profit (652,201 → 642,392) + reportDate (2021-01-31 → 2021-01-30)
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC 10-K comparative (FY2022 10-K, column 2021-01-30); Op Profit corrected for missing 9,809K pre-opening deduction

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'BJ''s', 2020, '2021-01-30',
  15430017, 12451061, 2978956, 2326755,
  642392, 421030, 1205695,
  1470581, 5411530, 2031212,
  5092203, 319327, 5411530
);

-- BJ FY2025 — New insert
-- Generated by /insert-financials on 2026-06-03
-- Source: SEC 10-K CIK 1531152 (period ending 2026-01-31) + Yahoo Finance (confirmed)
-- Note: Operating Profit = SEC Operating Income (816,604K) after deducting 29,441K pre-opening costs
--       Yahoo plain "Operating Income" (846,045K) excludes pre-opening — do not use

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'BJ''s', 2025, '2026-01-31',
  21457274, 17457652, 3999622, 3153577,
  816604, 578377, 1555471,
  1990089, 7510475, 2670233,
  5312816, 2197659, 7510475
);
