-- BJ FY 2025 — new insert
-- Generated by /insert-financials on 2026-05-29
-- Source: Yahoo Finance (column 2026-01-31); Operating Profit = Total Operating Income As Reported (BJ's convention)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'BJ''s', 2025, '2026-01-31',
  21457300, 17457700, 3999600, 3153580,
  816604, 578377, 1555470,
  1990090, 7510480, 2670230,
  5312820, 2197660, 7510480
);
