-- BOOT FY2024 — Correction: reportDate (2025-03-31 → 2025-03-29)
-- Generated by /insert-financials on 2026-06-06
-- Source: SEC

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Boot Barn', 2024, '2025-03-29',
  1911104, 1194066, 717038, 477686,
  239352, 180942, 747191,
  863960, 2018021, 353349,
  886964, 1131057, 2018021
);

-- BOOT FY2025 — New insert
-- Generated by /insert-financials on 2026-06-06
-- Source: SEC

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Boot Barn', 2025, '2026-03-28',
  2253859, 1395504, 858355, 559210,
  299145, 225880, 844637,
  1034399, 2450075, 390972,
  1131419, 1318656, 2450075
);
