-- BURL FY2022 — Operating Profit correction (583,135 → 307,509)
-- Generated by /insert-financials on 2026-06-06
-- Source: SEC

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Burlington', 2022, '2023-01-28',
  8702604, 5171715, 3530889, 2877356,
  307509, 230123, 1181982,
  2283792, 7269597, 1911951,
  6474692, 794905, 7269597
);

-- BURL FY2023 — Operating Profit correction (495,091 → 465,773)
-- Generated by /insert-financials on 2026-06-06
-- Source: SEC

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Burlington', 2023, '2024-02-03',
  9727467, 5584060, 4143407, 3288315,
  465773, 339649, 1087841,
  2327024, 7706840, 2028786,
  6709908, 996932, 7706840
);

-- BURL FY2025 — New year not yet in Dolt
-- Generated by /insert-financials on 2026-06-06
-- Source: SEC

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Burlington', 2025, '2026-01-31',
  11566910, 6486922, 5079988, 3817180,
  816118, 610153, 1311903,
  2771532, 9919057, 2249211,
  8111798, 1807259, 9919057
);
