-- CHWY FY 2022 — Correction: update to restated values from FY2023 10-K comparative column
-- Generated by /insert-financials on 2026-06-08
-- Source: SEC 10-K (CIK 1766502, FY2023 filing restated comparatives)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Chewy', 2022, '2023-01-29',
  10119000, 7284505, 2834495, 2128688,
  56421, 49899, 678005,
  1524780, 2519818, 1827718,
  2359550, 160268, 2519818
);

-- CHWY FY 2025 — New insert
-- Generated by /insert-financials on 2026-06-08
-- Source: SEC 10-K (CIK 1766502, FY ending 2026-02-01)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Chewy', 2025, '2026-02-01',
  12601500, 8847600, 3753900, 2674700,
  254300, 222800, 864800,
  2035800, 3366400, 2301600,
  2868500, 497900, 3366400
);
