-- COST FY 2019 — Correction: balance sheet fields were duplicated from FY2018 (Inventory, Current Assets, Total Assets, Current Liabilities, Liabilities, Total SE, Total L+SE)
-- Generated by /insert-financials on 2026-06-08
-- Source: SEC 10-K (CIK 909832, FY2020 10-K comparative column)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Costco', 2019, '2019-09-01',
  152703000, 132886000, 19817000, 14994000,
  4737000, 3659000, 11395000,
  23485000, 45400000, 23237000,
  29816000, 15584000, 45400000
);

-- COST FY 2025 — New insert
-- Generated by /insert-financials on 2026-06-08
-- Source: SEC 10-K (CIK 909832, FY ending 2025-08-31)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Costco', 2025, '2025-08-31',
  275235000, 239886000, 35349000, 24966000,
  10383000, 8099000, 18116000,
  38380000, 77099000, 37108000,
  47935000, 29164000, 77099000
);
