-- CPRI FY 2025 — New insert (FY ending 2026-03-28; Versace sold/reclassified, only Michael Kors + Jimmy Choo remain)
-- Generated by /insert-financials on 2026-06-08
-- Source: SEC 10-K (CIK 1530721)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Capri Holdings', 2025, '2026-03-28',
  3474000, 1311000, 2163000, 1964000,
  23000, 137000, 581000,
  1153000, 3234000, 954000,
  3150000, 84000, 3234000
);
