-- CVS FY 2019 — Correction: balance sheet fields (Current Assets, Current Liabilities, Liabilities, Total SE) were sourced from wrong column
-- Generated by /insert-financials on 2026-06-08
-- Source: SEC 10-K (CIK 64803)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'CVS', 2019, '2019-12-31',
  256776000, 158719000, 98057000, 33541000,
  11987000, 6634000, 17516000,
  50302000, 222449000, 53303000,
  158279000, 64170000, 222449000
);

-- CVS FY 2022 — Correction: Operating Profit and Net Profit updated to restated values from 2023 10-K (ASU adoption restatement)
-- Generated by /insert-financials on 2026-06-08
-- Source: SEC 10-K (CIK 64803, 2023 filing restated comparatives)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'CVS', 2022, '2022-12-31',
  322467000, 196892000, 125575000, 38212000,
  7954000, 4311000, 19090000,
  65682000, 228275000, 69736000,
  156960000, 71315000, 228275000
);
