-- DDS FY 2022 — Correction: Operating Profit (1,260,329 → 1,109,467, SEC pretax income)
-- Generated by /insert-financials on 2026-06-08
-- Source: SEC 10-K (CIK 28917, FY ending 2023-01-28)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Dillard''s', 2022, '2023-01-28',
  6996215, 3983598, 3012617, 1674317,
  1109467, 891637, 1120208,
  2071846, 3329150, 858961,
  1730512, 1598638, 3329150
);

-- DDS FY 2023 — Correction: Operating Profit (945,897 → 916,617, SEC pretax income)
-- Generated by /insert-financials on 2026-06-08
-- Source: SEC 10-K (CIK 28917, FY ending 2024-02-03)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Dillard''s', 2023, '2024-02-03',
  6874420, 4031108, 2843312, 1717415,
  916617, 738847, 1093999,
  2208210, 3448906, 827756,
  1751838, 1697068, 3448906
);

-- DDS FY 2024 — Correction: Net Revenue (6,482,636 → 6,590,231) and Gross Margin (2,563,087 → 2,670,682) — Dolt was using net sales only, missing service charges
-- Generated by /insert-financials on 2026-06-08
-- Source: SEC 10-K (CIK 28917, FY ending 2025-02-01)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Dillard''s', 2024, '2025-02-01',
  6590231, 3919549, 2670682, 1731234,
  729701, 593476, 1172047,
  2368070, 3531054, 834906,
  1734894, 1796160, 3531054
);

-- DDS FY 2025 — New insert
-- Generated by /insert-financials on 2026-06-08
-- Source: SEC 10-K (CIK 28917, FY ending 2026-01-31)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Dillard''s', 2025, '2026-01-31',
  6563336, 3916862, 2646474, 1759236,
  694480, 570187, 1201098,
  2386571, 3505023, 902084,
  1726053, 1778970, 3505023
);
