-- DKS FY 2019 — Correction: SGA had wrong sign (negative), and minor rounding on Net Revenue/Gross Margin
-- Generated by /insert-financials on 2026-06-08
-- Source: SEC 10-K (FY ending 2020-02-01)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Dick''s Sporting Goods', 2019, '2020-02-01',
  8750743, 6196185, 2554558, 2173677,
  375613, 297462, 2202275,
  2410016, 6628560, 2076474,
  4896962, 1731598, 6628560
);

-- DKS FY 2024 — Correction: reportDate (2025-02-03 → 2025-02-01)
-- Generated by /insert-financials on 2026-06-08
-- Source: SEC 10-K (FY ending 2025-02-01)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Dick''s Sporting Goods', 2024, '2025-02-01',
  13442849, 8617153, 4825696, 3294272,
  1473932, 1165308, 3349830,
  5417707, 10458694, 3080062,
  7260430, 3198264, 10458694
);

-- DKS FY 2025 — New insert (includes Foot Locker acquisition)
-- Generated by /insert-financials on 2026-06-08
-- Source: SEC 10-K (FY ending 2026-01-31)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Dick''s Sporting Goods', 2025, '2026-01-31',
  17215120, 11547858, 5667262, 4338162,
  1095909, 849239, 4907823,
  7104791, 17411499, 4643558,
  11871379, 5540120, 17411499
);
