-- DLTR FY 2023 — Correction: SGA included $1,069M goodwill impairment (10,213,600 → 9,144,600 clean SGA)
-- Generated by /insert-financials on 2026-06-08
-- Source: SEC 10-K (CIK 935703, FY ending 2024-02-03)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Dollar Tree', 2023, '2024-02-03',
  30603800, 21272000, 9331800, 9144600,
  -881800, -998400, 5112800,
  6132700, 22023500, 4696700,
  14710400, 7313100, 22023500
);

-- DLTR FY 2025 — New insert (single-segment Dollar Tree post-Family Dollar divestiture)
-- Generated by /insert-financials on 2026-06-08
-- Source: SEC 10-K (CIK 935703, FY ending 2026-01-31)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Dollar Tree', 2025, '2026-01-31',
  19411800, 12345000, 7066800, 5468600,
  1653100, 1282500, 2495400,
  3446200, 13466200, 3228600,
  9711300, 3754900, 13466200
);
