-- EBAY FY2025 — new insert
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC FY2025 10-K (primary); Yahoo Finance confirms all fields exactly
-- SGA = us-gaap_SellingAndMarketingExpense (2,394,000K) + us-gaap_GeneralAndAdministrativeExpense (1,198,000K) = 3,592,000K
-- R&D, transaction losses, and intangible amortization excluded from SGA per DB convention
-- Inventory NULL — pure marketplace, no physical goods held
-- NetInc = us-gaap_NetIncomeLoss = 2,031,000K (total including discontinued ops)
-- Balance sheet identity: 17,610,000 − 4,615,000 = 12,995,000 ✓

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'eBay', 2025, '2025-12-31',
  11100000, 3169000, 7931000, 3592000,
  2277000, 2031000, NULL,
  5086000, 17610000, 4637000,
  12995000, 4615000, 17610000
);
