-- REAL FY2020 — correction: SGA $196,575K → $195,465K (legal settlement reclassification)
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC FY2021 10-K restated comparative (legal settlement broken out separately per anomaly rules)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'The RealReal', 2020, '2020-12-31',
  299949, 112382, 187567, 195465,
  -172816, -175832, 42321,
  421469, 605109, 148260,
  413816, 191293, 605109
);

-- REAL FY2021 — minor correction: SGA $239,167K → $238,995K (−$172K per FY2023 10-K restatement)
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC FY2023 10-K restated comparative (most recent filing showing FY2021 data)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'The RealReal', 2021, '2021-12-31',
  467692, 194215, 273477, 238995,
  -214908, -236107, 71015,
  517812, 754944, 187986,
  681816, 73128, 754944
);

-- REAL FY2025 — new insert
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC FY2025 10-K + Yahoo Finance (fully consistent; SEC and Yahoo agree on all 13 fields)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'The RealReal', 2025, '2025-12-31',
  692845, 176023, 516822, 264840,
  -23934, -41799, 30843,
  227491, 409033, 264240,
  824551, -415518, 409033
);
