-- TSCO FY2020 — correction: Revenue $116,370K → $10,620,352K; Gross Margin −$6,742,433K → $3,761,549K
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC 2020 10-K (revenue was incorrectly entered as weighted-average shares outstanding value)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Tractor Supply', 2020, '2020-12-26',
  10620352, 6858803, 3761549, 2478524,
  996928, 748958, 1783270,
  3258685, 7049116, 1743798,
  5125276, 1923840, 7049116
);

-- TSCO FY2024 — correction: reportDate '2024-12-31' → '2024-12-28' (all financial values unchanged)
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC 2024 10-K (fiscal year ended 2024-12-28; prior entry used calendar year-end by mistake)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Tractor Supply', 2024, '2024-12-28',
  14883231, 9486674, 5396557, 3481863,
  1467532, 1101240, 2840177,
  3309917, 9805485, 2319193,
  7535151, 2270334, 9805485
);

-- TSCO FY2025 — new insert
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC 2025 10-K + Yahoo Finance (agree within $21K rounding on all fields)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Tractor Supply', 2025, '2025-12-27',
  15524046, 9869538, 5654508, 3693108,
  1467389, 1096087, 3084086,
  3507797, 10933679, 2614449,
  8352386, 2581293, 10933679
);
