-- ULTA FY2025 — new insert
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC 2025 10-K (reportDate 2026-01-31); Yahoo agrees on all fields except Operating Profit
-- Note: Yahoo OpProfit $1,548,810K overstates by $15,821K (excludes pre-opening costs); use SEC $1,532,992K

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Ulta Beauty', 2025, '2026-01-31',
  12392820, 7547596, 4845224, 3296411,
  1532992, 1153479, 2181127,
  3144146, 6999294, 2224342,
  4195843, 2803451, 6999294
);
