-- URBN FY2019 — correction: SGA −993,990K → +993,990K (sign flip data entry error)
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC FY2019 10-K (2020-01-31); all other fields confirmed correct in Dolt
-- Note: Gross Margin = Revenue − COGS only (excludes store impairment $14,611K per URBN DB approach)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Urban Outfitters', 2019, '2020-01-31',
  3983789, 2729352, 1254437, 993990,
  231925, 168096, 409534,
  1053396, 3315633, 638770,
  1860278, 1455355, 3315633
);

-- URBN FY2025 — new insert
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC FY2025 10-K (2026-01-31); Yahoo agrees on OpInc and NetInc exactly
-- Note: Gross Margin = Revenue − COGS only ($6,165,376K − $3,945,634K); excludes store impairment $1,989K per URBN DB approach
-- Note: Yahoo COGS ($3,947,620K) includes store impairment; SEC COGS ($3,945,634K) used

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Urban Outfitters', 2025, '2026-01-31',
  6165376, 3945634, 2219742, 1612119,
  605634, 464919, 700945,
  1686104, 5007613, 1118094,
  2192326, 2815287, 5007613
);
