-- VSCO FY2020 — correction: reportDate '2021-01-31' → '2021-01-30' (L Brands fiscal year end was Jan 30, not Jan 31)
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC FY2021 10-K comparative (confirms fiscal year end 2021-01-30); income statement verified; balance sheet accepted as-is (pre-spinoff carve-out, unverifiable from standalone 10-K)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Victoria''s Secret', 2020, '2021-01-30',
  5413000, 3842000, 1571000, 1672000,
  -101000, -72000, 701000,
  1239000, 4229000, 1556000,
  3338000, 891000, 4229000
);

-- VSCO FY2023 — correction: NetProfit $116,000K → $109,000K (was us-gaap_ProfitLoss, correct is us-gaap_NetIncomeLoss)
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC FY2023 10-K (2024-02-03); confirmed by Yahoo Finance ($109K) and EPS × shares check
-- NCI income $7,000K: ProfitLoss $116,000K − NCI $7,000K = NetIncomeLoss $109,000K (to common shareholders)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Victoria''s Secret', 2023, '2024-02-03',
  6182000, 3940000, 2242000, 1996000,
  246000, 109000, 985000,
  1533000, 4600000, 1614000,
  4183000, 417000, 4600000
);

-- VSCO FY2024 — correction: TSE $664,000K → $640,000K; Liab $3,868,000K → $3,892,000K (minority interest misclassification)
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC FY2024 10-K (2025-02-01); Yahoo Finance confirms Common Stock Equity = $640,000K
-- DB convention: TSE = us-gaap_StockholdersEquity (common only); Liab = TA − TSE (includes $24K minority)
-- Prior Dolt entry used StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest ($664K) — inconsistent with FY2022/FY2023

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Victoria''s Secret', 2024, '2025-02-01',
  6230000, 3946000, 2284000, 1974000,
  310000, 165000, 955000,
  1441000, 4532000, 1375000,
  3892000, 640000, 4532000
);

-- VSCO FY2025 — new insert
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC FY2025 10-K (2026-01-31); Yahoo Finance agrees on all fields exactly
-- TSE = us-gaap_StockholdersEquity $856,000K (common only); Liab = TA − TSE = $5,013,000K − $856,000K = $4,157,000K (includes $54K minority interest)
-- NetInc = us-gaap_NetIncomeLoss $161,000K (to common); ProfitLoss $189,000K − NCI $28,000K = $161,000K

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Victoria''s Secret', 2025, '2026-01-31',
  6553000, 4169000, 2384000, 2113000,
  271000, 161000, 1071000,
  1883000, 5013000, 1507000,
  4157000, 856000, 5013000
);
