-- W FY2024 — correction: SGA 4,035,000K → 1,977,000K
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC FY2025 10-K (year=2025) 2024 comparative; SEC FY2024 10-K (year=2024) primary
-- Prior Dolt entry used us-gaap_OperatingExpenses (total: CustomerService $470M + Marketing $1,472M
--   + SOTG&A $1,977M + Impairment $37M + Restructuring $79M = $4,035M) as SGA
-- DB convention (established years 2018-2023): SGA = w_SellingTechnologyOperationsGeneralAndAdministrativeExpense only
-- All other fields unchanged (OpInc, NetInc, balance sheet all verified correct)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Wayfair', 2024, '2024-12-31',
  11851000, 8277000, 3574000, 1977000,
  -461000, -492000, 76000,
  1877000, 3459000, 2370000,
  6214000, -2755000, 3459000
);

-- W FY2025 — new insert (fiscal year ending 2025-12-31)
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC FY2025 10-K (year=2025); Yahoo Finance confirms Revenue, COGS, Gross, NetInc, BS
-- SGA = w_SellingTechnologyOperationsGeneralAndAdministrativeExpense = $1,776M (SOTG&A only)
-- OpInc = us-gaap_OperatingIncomeLoss = $17M (as-reported; Yahoo normalized OpInc = $93M excludes
--   restructuring $53M and impairment $23M — not used)
-- NetInc = us-gaap_NetIncomeLoss = -$313M (Wayfair has no NCI; no parent/NCI split needed)
-- TSE = us-gaap_StockholdersEquity = -$2,782M (negative; persistent accumulated deficit, expected)
-- Liab = TA - TSE = 3,440,000 - (-2,782,000) = 6,222,000K

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Wayfair', 2025, '2025-12-31',
  12457000, 8692000, 3765000, 1776000,
  17000, -313000, 71000,
  2001000, 3440000, 2129000,
  6222000, -2782000, 3440000
);
