-- WBA FY2022 — correction: NetProfit $4,065,000K → $4,337,000K (was us-gaap_ProfitLoss, correct is us-gaap_NetIncomeLoss)
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC FY2024 10-K comparative (2022-08-31 column) per restatement rule
-- NCI entities (VillageMD, CityMD, Shields) had net losses of $271,000K absorbed by minority investors
-- ProfitLoss $4,065,000K + NCI loss $271,000K = NetIncomeLoss $4,337,000K (to parent)
-- Balance sheet accepted as-is (SEC FY2022 10-K unverifiable from MCP; identity holds)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Walgreens', 2022, '2022-08-31',
  132703000, 104437000, 28266000, 27295000,
  1387000, 4337000, 8353000,
  16902000, 90124000, 22583000,
  64849000, 25275000, 90124000
);

-- WBA FY2023 — correction: NetProfit −$3,528,000K → −$3,080,000K (was us-gaap_ProfitLoss, correct is us-gaap_NetIncomeLoss)
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC FY2024 10-K comparative (2023-08-31 column) per restatement rule
-- NCI entities had net losses of $448,000K absorbed by minority investors (VillageMD/CityMD losses)
-- ProfitLoss −$3,528,000K + NCI loss $448,000K = NetIncomeLoss −$3,080,000K (to parent)
-- Balance sheet accepted as-is (SEC FY2023 10-K unverifiable from MCP; identity holds)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Walgreens', 2023, '2023-08-31',
  139081000, 112009000, 27072000, 34205000,
  -6882000, -3080000, 8257000,
  15503000, 96628000, 24535000,
  68306000, 28322000, 96628000
);

-- WBA FY2024 — correction: Liab $68,992,000K → $69,032,000K (balance identity failure)
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC FY2024 10-K (2024-08-31)
-- Prior Dolt entry: Liab $68,992K + TSE $12,005K = $80,997K ≠ TA $81,037K (off by $40K)
-- Correct Liab = TA − TSE = $81,037K − $12,005K = $69,032K
-- = SEC Total Liabilities $68,858K + Redeemable NCI $174K (absorbed into DB Liabilities per convention)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Walgreens', 2024, '2024-08-31',
  147658000, 121134000, 26524000, 28113000,
  -14076000, -8636000, 8320000,
  18335000, 81037000, 26953000,
  69032000, 12005000, 81037000
);
