-- WMT FY2018 — correction: TSE $79,634,000K → $72,496,000K; Liab $139,661,000K → $146,799,000K
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC year=2018 10-K (2019-01-31 balance sheet)
-- Prior Dolt entry used StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest ($79,634K = common $72,496K + NCI $7,138K)
-- DB convention: TSE = us-gaap_StockholdersEquity (common only); NCI absorbed into Liab = TA - TSE
-- Income statement verified and unchanged

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Walmart', 2018, '2019-01-31',
  514405000, 385301000, 129104000, 107147000,
  21957000, 6670000, 44269000,
  61897000, 219295000, 77477000,
  146799000, 72496000, 219295000
);

-- WMT FY2019 — correction: Revenue $519,926,000K → $523,964,000K; Gross $125,321,000K → $129,359,000K;
--   TSE $81,552,000K → $74,669,000K; Liab $154,943,000K → $161,826,000K
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC year=2019 10-K (2020-01-31); confirmed in year=2020 10-K comparative
-- Revenue error: Dolt used us-gaap_RevenueFromContractWithCustomerExcludingAssessedTax ($519,926K)
--   instead of us-gaap_Revenues ($523,964K = contract $519,926K + membership/other income $4,038K)
-- Proof: Revenue - COGS - SGA = 523,964 - 394,605 - 108,791 = 20,568 = OpInc ✓ (519,926 would give 16,530 ≠ 20,568)
-- TSE error: Dolt used total equity incl. NCI ($81,552K = common $74,669K + NCI $6,883K)
-- DB convention: TSE = common SE; Liab = TA - TSE = 236,495 - 74,669 = 161,826K

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Walmart', 2019, '2020-01-31',
  523964000, 394605000, 129359000, 108791000,
  20568000, 14881000, 44435000,
  61806000, 236495000, 77790000,
  161826000, 74669000, 236495000
);

-- WMT FY2024 — correction: TSE $97,421,000K → $91,013,000K; Liab $163,402,000K → $169,810,000K
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC year=2024 10-K (2025-01-31 balance sheet); Yahoo confirms Common Stock Equity = $91,013K
-- Prior Dolt entry used StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest ($97,421K = common $91,013K + NCI $6,408K)
-- DB convention: TSE = us-gaap_StockholdersEquity (common only); Liab = TA - TSE = 260,823 - 91,013 = 169,810K
-- (= SEC total liabilities $163,131K + Redeemable NCI $271K + Non-redeemable NCI $6,408K = 169,810K)
-- Income statement verified and unchanged

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Walmart', 2024, '2025-01-31',
  680985000, 511753000, 169232000, 139884000,
  29348000, 19436000, 56435000,
  79458000, 260823000, 96584000,
  169810000, 91013000, 260823000
);

-- WMT FY2025 — new insert (fiscal year ending 2026-01-31)
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC year=2025 10-K (2026-01-31); Yahoo Finance confirms all fields (SGA was NaN in Yahoo — use SEC)
-- Revenue: us-gaap_Revenues $713,163K = contract $706,413K + membership/other $6,750K
-- NetInc: us-gaap_NetIncomeLoss $21,893K = ProfitLoss $22,270K - NCI income $377K
-- TSE: us-gaap_StockholdersEquity $99,617K (common only, per DB convention)
-- Liab = TA - TSE = 284,668 - 99,617 = 185,051K (= total liab $178,488K + Redeemable NCI $293K + NCI $6,270K)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Walmart', 2025, '2026-01-31',
  713163000, 535395000, 177768000, 147943000,
  29825000, 21893000, 58851000,
  84874000, 284668000, 107469000,
  185051000, 99617000, 284668000
);
