-- WSM FY2018 — correction: SGA −1,665,060K → +1,665,060K (sign error)
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: internal consistency (Gross 2,101,013 − |SGA| 1,665,060 = OpInc 435,953 ✓)
-- SGA was stored as negative (−1,665,060K) — likely entered with SEC income statement sign convention
-- DB convention: SGA must be positive. All other fields unchanged.

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Williams-Sonoma', 2018, '2019-02-03',
  5671593, 3570580, 2101013, 1665060,
  435953, 333684, 1124992,
  1694343, 2812844, 1074812,
  1657130, 1155714, 2812844
);

-- WSM FY2024 — correction: reportDate 2025-01-28 → 2025-02-02
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC FY2025 10-K (year=2025) — period header shows 2025-02-02 for FY2024
-- WSM fiscal year ends the Sunday nearest February 1; in 2025 that was February 2, 2025
-- Financial data is all correct and unchanged — only reportDate needed updating

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Williams-Sonoma', 2024, '2025-02-02',
  7711541, 4129242, 3582299, 2152115,
  1430184, 1125251, 1332429,
  2754609, 5301607, 1911974,
  3159188, 2142419, 5301607
);

-- WSM FY2025 — new insert (fiscal year ending 2026-02-01)
-- Generated by /create-verified-dolt-db-financials-sql on 2026-06-08
-- Source: SEC FY2025 10-K (year=2025); Yahoo Finance confirms all fields (minor rounding only)
-- Revenue: us-gaap_RevenueFromContractWithCustomerExcludingAssessedTax = 7,806,816K
-- COGS: us-gaap_CostOfRevenue = 4,203,765K (newer tag; older filings used wsm_CostOfGoodsSoldAndOccupancyExpenses)
-- SGA: us-gaap_SellingGeneralAndAdministrativeExpense = 2,187,329K (single combined line)
-- No NCI. TSE = us-gaap_StockholdersEquity = 2,082,559K
-- Liab = TA − TSE = 5,411,912 − 2,082,559 = 3,329,353K ✓

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'Williams-Sonoma', 2025, '2026-02-01',
  7806816, 4203765, 3603051, 2187329,
  1415722, 1088437, 1462849,
  2713187, 5411912, 1954130,
  3329353, 2082559, 5411912
);
