-- YETI FY2024 — reportDate correction (2024-12-31 → 2024-12-28)
-- Generated by /insert-financials on 2026-04-29
-- Source: SEC 10-K (fiscal year end per filing header: 2024-12-28)

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'YETI', 2024, '2024-12-28',
  1829873, 766589, 1063284, 817908,
  245376, 175689, 310058,
  826766, 1286120, 379504,
  546013, 740107, 1286120
);

-- YETI FY2025 — new insert
-- Generated by /insert-financials on 2026-04-29
-- Source: SEC 10-K (fiscal year end 2026-01-03; 52/53-week year); confirmed by Yahoo Finance

REPLACE INTO financials (
  company_name, year, reportDate,
  `Net Revenue`, `Cost of Goods`, `Gross Margin`, `SGA`,
  `Operating Profit`, `Net Profit`, `Inventory`,
  `Current Assets`, `Total Assets`, `Current Liabilities`,
  `Liabilities`, `Total Shareholder Equity`,
  `Total Liabilities and Shareholder Equity`
) VALUES (
  'YETI', 2025, '2026-01-03',
  1868494, 795810, 1072684, 859127,
  213557, 165387, 290611,
  660326, 1235418, 334339,
  585142, 650276, 1235418
);
